spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:  #zuul配置
  routes:  #路由
    api-a:  #api-a 名称可自取
      path: /api/a/**  #路径,*代表全目录匹配
      serviceId: hello-spring-cloud-web-admin-ribbon   #需要聚合服务的name
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign